name: Build Package

on:
  push:
    tags:
      - 'v*'

jobs:
  conda-build:
    uses: JoseAngelMartinB/github_actions/.github/workflows/conda-build.yml@main
    secrets:
      ANACONDA_TOKEN: {% raw %}${{ secrets.ANACONDA_TOKEN }}{% endraw %}
    with:
      package_name: {{ cookiecutter.package_name }}